### Ejercicios de codificación

Este cuaderno se encuentra en:

https://github.com/gbonorino/PythonIntegral/tree/main/Biblioteca_numpy

#### Ejercicio 1
Dado el array unidimensional: <br>
arr = np.arange(27)<br>
modificar arr para obtener un array con shape 3,3,3

#### Ejercicio 2
Combinar dos arrays horizontalmente, i.e., mantener el numero de filas

arr1 = np.array([[1,2,3],[4,5,6]])

arr2 = np.array([[7,8,9],[10,11,12]])

#### Ejercicio 3
Crear un array 3 x 3 con números aleatorios de una distribución normal

### Soluciones

In [17]:
# Ejercicio 1
import numpy as np

arr = np.arange(27)
res = arr.reshape(3,3,3)
print(res)
res.ndim

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


3

In [18]:
# Ejercicio 2
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
res = np.hstack((arr1, arr2))
res

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [19]:
# Ejercicio 3
import numpy as np

res = np.random.normal(size = (3,3))
res

array([[ 0.2590267 ,  1.76420225, -1.03372217],
       [-1.32980431, -0.8731948 ,  0.41902754],
       [ 0.73174241,  1.38115586,  1.18957217]])